name: Push DV to GHCR and deploy to EKS

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  pushToGHCR:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pushing DV to GHCR
      env:
        VERSION: ${{ github.sha }}
        IMAGE: ghcr.io/open-earth-foundation/ccglobal-data-viewer
      run: |
        docker build -t $IMAGE:$VERSION .
        docker tag $IMAGE:$VERSION $IMAGE:latest
        docker push $IMAGE:$VERSION
        docker push $IMAGE:latest
